# Generated by Django 2.1.1 on 2020-09-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuringInstrument', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='business_number',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대전', '대전'), ('대구', '대구'), ('인천', '인천'), ('강릉', '강릉')], max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='area',
            name='areaUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
    ]
