# Generated by Django 2.1.1 on 2020-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200919_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='areaUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='business_number',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대전', '대전'), ('대구', '대구'), ('인천', '인천'), ('강릉', '강릉')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
