# Generated by Django 2.1.1 on 2020-09-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200912_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='user',
            new_name='areaUser',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='author',
            new_name='measuringInstrument',
        ),
        migrations.AlterField(
            model_name='user',
            name='business_number',
            field=models.CharField(choices=[('서울', '서울'), ('부산', '부산'), ('대전', '대전'), ('대구', '대구'), ('인천', '인천'), ('강릉', '강릉')], max_length=30, null=True, unique=True),
        ),
    ]
