# Generated by Django 2.1.1 on 2020-09-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measuringInstrument', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('areaUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areaUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
